# Generated by Django 5.2.3 on 2026-01-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_material_productmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='product/main-image/'),
        ),
    ]
